### ISSUE TITLE
Reorganizar diretórios e exclusão de arquivos inúteis.

### ISSUE THREAD

**Issue by leosch92** [vitornl/CheckErS2#12]
Como dito anteriormente, precisamos reorganizar os diretórios de modo a deixar apenas uma pasta de código (src), excluindo a pasta code, que gera conflito com a biblioteca code nativa do python:
https://docs.python.org/3/library/code.html?highlight=code#module-code

Além disso, existem arquivos aparentemente temporários chamados '_ _init_ _' que fazem com que o debugger do PyCharm não funcione. Se não há utilidade neles, favor excluir antes de commitar o projeto. Caso haja utilidade, favor informar como comentário dessa issue. Abs

**Comment by vitornl** [comment]
Analisado e concluído
