### ISSUE TITLE
Movimentação de Damas incorreta

### ISSUE THREAD

**Issue by arthurFerraz9** [vitornl/CheckErS2#14]
A dama pode se mover para qualquer diagonal em qualquer quantidade.

Além disso ela terá qeu ser adaptada para utilização de Movement.

**Comment by VitorA29** [comment]
Com o #25 agora as damas não possuem movimentação nenhuma

**Comment by VitorA29** [comment]
Comecei a movimentação ainda pouco

**Comment by VitorA29** [comment]
Tentei fazer direto com a opção escolher onde parar ela apos comer a peça, não consegui. Na branch enhancement/draught_movement ela come peça igual peça normal

**Comment by vitornl** [comment]
Corrigido.
