### ISSUE TITLE
Ao selecionar 2 vezes seguidas peças inválidas, jogo trava

### ISSUE THREAD

**Issue by vitornl** [vitornl/CheckErS2#18]
Cenário de teste:
Digite a peça a ser jogada: 0 0
--inválido--
Digite a peça a ser jogada: 0 0
Traceback (most recent call last):
  File "run.py", line 49, in <module>
  File "run.py", line 17, in main
    piece_position = Util.string_to_int_tuple(input("Digite a peça a ser jogada: "))
  File "**\CheckErS2\src\code\Controller\util.py", line 5, in string_to_int_tuple
    tup = tuple(map(int, string.split(" ")))
ValueError: invalid literal for int() with base 10: ''

**Comment by arthurFerraz9** [comment]
Provavelmente ele tá pegando o '\n' da entrada anterior. Lembro de ter problemas similares com isso em Pyhton.
