### ISSUE TITLE
Peças não são obrigadas a comer

### ISSUE THREAD

**Issue by vitornl** [vitornl/CheckErS2#19]
Cenário exemplo:
red 4 5-> 3 4
blue 1 2 -> 2 3
red 2 5 -> 1 4
era para ser obrigatório selecionar a a peça em red(3, 4) e comer a blue(2, 3)

**Comment by arthurFerraz9** [comment]
Pelo que eu entendi isso deveria ser outra história. O que eu acho que faz sentido, pois a eliminação não obrigatória já entrega valor para o cliente.

**Comment by vitornl** [comment]
Não, não faz sentido. Isso é obrigatório do jogo, as regras explicitam (regra sobre 'soprar'). Não é uma adição, é um bug.

**Comment by arthurFerraz9** [comment]
Eu não disse que não é obrigatório para o jogo. Mas comer peça é funcionalidade que já entrega valor. A regra de soprar é outra funcionalidade.

**Comment by VitorA29** [comment]
Tornar obrigatório comer uma peça é função do avaliador de jogadas, entre fazer uma jogada e jogar, tem que ter um filtro de possibilidades pra forçar isso

**Comment by vitornl** [comment]
Realizado
