### ISSUE TITLE
Bug na condição de vitoria

### ISSUE THREAD

**Issue by VitorA29** [vitornl/CheckErS2#28]
`File "run.py", line 68, in <module>
    main()
  File "run.py", line 16, in main
    while (rules.win_condition()):
  File "C:\Users\vitor\Documents\GitHub\TCC00293-ES2\src\code\Controller\rules.py", line 295, in win_condition
    if possibilities.__contains__(piece):
AttributeError: 'NoneType' object has no attribute '__contains__'`
Esse traceback aconteceu quando um dos jogadores ficou sem peças jogáveis

**Comment by leosch92** [comment]
Bug corrigido na branch bugfix/#28,#30. Favor verificar o pull request.

**Comment by leosch92** [comment]
Bug corrigido na branch bugfix/#28,#30. Favor verificar o pull request.
