### ISSUE TITLE
"Arrependimento" do jogador em uma eliminação múltipla

### ISSUE THREAD

**Issue by leosch92** [vitornl/CheckErS2#44]
Em uma eliminação múltipla, caso clique em algum lugar a partir da segunda comida que não seja a casa correspondente à captura, a peça para no meio da eliminação, tendo executado uma jogada que apenas pulou a primeira peça capturada, e essa também não é eliminada.

**Comment by VitorA29** [comment]
na real, não é em qualquer lugar, é na posição original da peça
