### ISSUE TITLE
Segmentation fault ao sair do jogo

### ISSUE THREAD

**Issue by leosch92** [vitornl/CheckErS2#62]
Ao sair do jogo no meio da partida, o programa não finaliza. Depois de alguns segundos aparece um erro de segmentation fault no console.

![bug_segmentation](https://user-images.githubusercontent.com/12973094/41100601-3499c3d2-6a38-11e8-936d-856ac2f64af9.png)

**Comment by vitornl** [comment]
É um problema comum relativo ao pygame, no game loop não definimos uma saída sem ser a do fim do jogo.
